# site configuration

exclude: [Gemfile, Gemfile.lock, README.md, LICENSE]
permalink: pretty
pygments: true

author: Richard Mortier
settings:
  github: hdiresearch/hdiresearch.github.io
  analytics:
    id: UA-45397197-1
    name: hdiresearch.org
