# site configuration

exclude: [_less, _coffee, Gemfile, Gemfile.lock, README.md, LICENSE]
permalink: pretty
pygments: true

github: hdiresearch/hdiresearch.github.io
analytics_id: UA-XXXXXXX

author: Richard Mortier
